# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.srcs/sources_1/ip/output_buffer/output_buffer.xci
# IP: The module: 'output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.gen/sources_1/ip/output_buffer/output_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.gen/sources_1/ip/output_buffer/output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.srcs/sources_1/ip/output_buffer/output_buffer.xci
# IP: The module: 'output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.gen/sources_1/ip/output_buffer/output_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_prj/capstone2/imageprocessing/imageprocessing.gen/sources_1/ip/output_buffer/output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
